-- 幂等初始化脚本：表已存在则跳过建表，表已有数据则跳过种子数据，可安全重复执行。
-- 用法（容器启动完成后）：
--   docker exec -it $(docker ps -qf "name=db2") bash -c \
--     "su - db2inst1 -c 'db2 connect to testdb && db2 -tf /init/init-db.sql'"
-- 如需彻底重置（含清空 CDC 历史变更日志），请使用 docker compose down -v，见 README。
-- CDC 捕获的自动开启由 /init/init-cdc.sh 完成（asncap 启动需等待，纯 SQL 无法处理，
-- 执行完本脚本后再执行 bash /init/init-cdc.sh 即可提交 Flink 作业）。

--#SET TERMINATOR @

-- 条件建表：仅当 PRODUCTS 不存在时创建
BEGIN
  IF NOT EXISTS (SELECT 1 FROM SYSCAT.TABLES
                 WHERE TABSCHEMA = 'DB2INST1' AND TABNAME = 'PRODUCTS') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE DB2INST1.PRODUCTS (
        ID          INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        NAME        VARCHAR(64) NOT NULL,
        DESCRIPTION VARCHAR(255),
        WEIGHT      DECIMAL(10,3),
        PRIMARY KEY (ID)
      ) DATA CAPTURE CHANGES';
  END IF;
END@

--#SET TERMINATOR ;

-- 条件插入种子数据：仅当表为空时写入（ID 101-109，共 9 条；README mock 中的
-- white wind breaker / Big 2-wheel scooter 故意不在种子数据里，作为增量 INSERT 验证用）
INSERT INTO DB2INST1.PRODUCTS (NAME, DESCRIPTION, WEIGHT)
SELECT seed.NAME, seed.DESCRIPTION, seed.WEIGHT
FROM (
  SELECT 'scooter',            'Small 2-wheel scooter',                         DECIMAL(3.14, 10, 3)  FROM SYSIBM.SYSDUMMY1 UNION ALL
  SELECT 'car battery',        '12V car battery',                               DECIMAL(8.1, 10, 3)   FROM SYSIBM.SYSDUMMY1 UNION ALL
  SELECT '12-pack drill bits', '12-pack of drill bits with sizes ranging from #40 to #3', DECIMAL(0.8, 10, 3) FROM SYSIBM.SYSDUMMY1 UNION ALL
  SELECT 'hammer',             '12oz carpenters hammer',                        DECIMAL(0.75, 10, 3)  FROM SYSIBM.SYSDUMMY1 UNION ALL
  SELECT 'hammer',             '14oz carpenters hammer',                        DECIMAL(0.875, 10, 3) FROM SYSIBM.SYSDUMMY1 UNION ALL
  SELECT 'hammer',             '16oz carpenters hammer',                        DECIMAL(1.0, 10, 3)   FROM SYSIBM.SYSDUMMY1 UNION ALL
  SELECT 'rocks',              'box of assorted rocks',                         DECIMAL(5.3, 10, 3)   FROM SYSIBM.SYSDUMMY1 UNION ALL
  SELECT 'jacket',             'water resistent black wind breaker',            DECIMAL(0.1, 10, 3)   FROM SYSIBM.SYSDUMMY1 UNION ALL
  SELECT 'spare tire',         '24 inch spare tire',                            DECIMAL(22.2, 10, 3)  FROM SYSIBM.SYSDUMMY1
) AS seed (NAME, DESCRIPTION, WEIGHT)
WHERE NOT EXISTS (SELECT 1 FROM DB2INST1.PRODUCTS);

COMMIT;
